galaxy_info:
  author: Evan Nook
  description: Setup Debian base system
  company: InnoNook
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
  galaxy_tags:
    - system
    - base
    - debian
dependencies: []
